export const AUTH_FETCH = 'AUTH_FETCH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const RESOURCE_FETCH = 'RESOURCE_FETCH';
export const RESOURCE_FETCH_SUCCESS = 'RESOURCE_FETCH_SUCCESS';
export const RESOURCE_FETCH_FAILED = 'RESOURCE_FETCH_FAILED';

export const RESOURCE_CHILDS_FETCH = 'RESOURCE_CHILDS_FETCH';
export const RESOURCE_CHILDS_FETCH_SUCCESS = 'RESOURCE_CHILDS_FETCH_SUCCESS';
export const RESOURCE_CHILDS_FETCH_FAILED = 'RESOURCE_CHILDS_FETCH_FAILED';

export const START_FETCHING_RESOURCES = 'START_FETCHING_RESOURCES';

export const CHANGE_RESOURCE_COLLAPSED_STATE = 'CHANGE_RESOURCE_COLLAPSED_STATE';
