export const AUTH_FETCH = 'AUTH_FETCH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const RESOURCE_FETCH = 'RESOURCE_FETCH';
export const RESOURCE_FETCH_SUCCESS = 'RESOURCE_FETCH_SUCCESS';
export const RESOURCE_FETCH_FAILED = 'RESOURCE_FETCH_FAILED';
